# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CineTrack' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CineTrack
	pod 'FirebaseAuth'
        pod 'FirebaseFirestore'
	pod 'FirebaseAnalytics'

  target 'CineTrackTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CineTrackUITests' do
    # Pods for testing
  end

end
